ARG BALENA_ARCH=%%BALENA_ARCH%%

# https://github.com/klutchell/balena-tailscale
FROM bh.cr/gh_klutchell/tailscale-amd64/86ec96d36b9b4ec83c108c3ec111fb5c:1.96.4-rev6 AS balena-tailscale-amd64
FROM bh.cr/gh_klutchell/tailscale-aarch64/873c3a5cf3fa924467c82551a057f9d2:1.96.4-rev6 AS balena-tailscale-aarch64
FROM bh.cr/gh_klutchell/tailscale-armv7hf/04fdf8fc53338f7ff63dc547569d591c:1.96.4-rev6 AS balena-tailscale-armv7hf

# hadolint ignore=DL3006
FROM balena-tailscale-${BALENA_ARCH}

ENV TS_HOSTNAME="adguard"
ENV TS_EXTRA_ARGS="--accept-dns=false --reset"
